### PR TITLE
Define ODataExpression for getting object with ODataV4QuerySegments

### PR DESCRIPTION
**Pull request by mildronize**
From my proposal #27, I would like to submit the PR for improve the code,

Please review the code, any suggest are welcome,

I've attached the coverage test on my local machine
CleanShot 2567-01-10 at 12 16 40@2x

### CODE REVIEW

**Comment by cbrianball** [comment]
Hey, thanks for the PR! Apologies for not responding to the issue you filed a couple of days ago. I like the idea -- it makes sense to be able to build the expression without having any knowledge of a base path/URL.

Over the next couple of days I'll try to find time to pull this down locally and fully wrap my head around the changes and see if it makes sense as-is or if there needs to be some tweaks.

I'm currently in the process of implementing support for async iterables (e.g., `for await ... of`), but that shouldn't have any impact on your suggestion since you aren't providing any new ways of executing OData queries within the library itself (just a way for consumers to get the relevant OData query so that they can attach it to their own path/URL).

**Comment by cbrianball** [comment]
I like what I see. Please run `npm run lint:fix` and push those changes. Also, can you update the `readme.md` file to briefly explain the new types and an example of how they can be used.

Thank you for your work!

**Comment by mildronize** [comment]
Thank you so much for your suggestion; that is a great idea to run lint (which I had already forgotten). However, I've fixed it with lint and updated the `README.md`.

Feel free to suggest anything; somehow, I don't understand your intention in the code. I try to guess what you think behind it. If something and the naming convention don't meet your standards, please let me know.

I'm very excited to see the new package version.

**Comment by cbrianball** [comment]
Thank you so much! I plan to push a new version of the package in the next 2 - 3 days.

**Pull request merged**
